[versions]
kotlin = "2.3.0"
coroutines = "1.10.2"

[libraries]
scryfall-api = { module = "io.github.devmugi:scryfall-api", version = "1.0.0" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
